### ISSUE TITLE
handle non-header enum definitions

### ISSUE THREAD

**Issue by oldgalileo** [xlab/nl80211#1]
I wasn't sure whether to leave this as an issue on [c-for-go](https://github.com/xlab/c-for-go/issues) or here, but alas.

Unfortunately, it looks as though the multicast group IDs weren't defined in nl80211.h but in [nl80211.c](https://github.com/torvalds/linux/blob/master/net/wireless/nl80211.c#L38) as an enum. It's also not static, which just makes it even more complicated.

Of course manually editing the generated const.go is less-than-stellar, so I've defined it as constants within one of my normal files. Any alternatives or ways of using c-for-go to get around this would be amazing.

**Comment by xlab** [comment]
Hi @HowardStark, the best way to do that is to create a standalone `.h` file and put it there, as c-for-go doesn't work with .c files by design. Sorry about that :)

Also, c-for-go doesn't try to be fully automatic and stellar, it's a tool that does most of the job, however sometimes you should fix things like this issue manually.
